<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Game.Core\GameCore.csproj" />
    <ProjectReference Include="..\GameScenarios\GameScenarios.csproj" />
  </ItemGroup>

</Project>
